import { db } from '@/db';
import { products } from '@/db/schema';

async function main() {
    const sampleProducts = [
        {
            slug: '1000-wala',
            name: '1000 Wala',
            description: 'Traditional 1000 wala firecracker chain that creates a spectacular display of continuous bursts. Perfect for Diwali celebrations and weddings. Made with high-quality materials for safe and prolonged enjoyment.',
            categoryId: 1,
            sku: 'FC1000',
            stock: 500,
            status: 'active',
            unit: 'box',
            tags: JSON.stringify(['diwali', 'festival', 'popular', 'traditional', 'weddings']),
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            slug: '10000-wala',
            name: '10000 Wala',
            description: 'Premium 10000 wala mega firecracker chain for grand celebrations. Creates an extraordinary fireworks show with thousands of crackling sounds. Must-have for major festivals and special occasions.',
            categoryId: 1,
            sku: 'FC10000',
            stock: 200,
            status: 'active',
            unit: 'box',
            tags: JSON.stringify(['diwali', 'festival', 'mega-pack', 'premium', 'grand-celebrations']),
            createdAt: new Date('2024-01-16').toISOString(),
            updatedAt: new Date('2024-01-16').toISOString(),
        },
        {
            slug: 'sparkler-10-inch',
            name: 'Sparkler 10 inch',
            description: 'Safe and colorful sparklers perfect for children and families. 10-inch length provides excellent burn time for celebrations. CE certified sparklers that emit beautiful golden sparks without smoke.',
            categoryId: 2,
            sku: 'SP10',
            stock: 1000,
            status: 'active',
            unit: 'pack',
            tags: JSON.stringify(['sparklers', 'kids-safe', 'family', 'diwali', 'colorful']),
            createdAt: new Date('2024-01-17').toISOString(),
            updatedAt: new Date('2024-01-17').toISOString(),
        },
        {
            slug: 'sparkler-15-inch-gold',
            name: 'Sparkler 15 inch Gold',
            description: 'Premium golden sparklers with extended 15-inch length for longer celebration time. Creates spectacular golden showers of sparks. Perfect for weddings, receptions, and grand festivities.',
            categoryId: 2,
            sku: 'SP15G',
            stock: 800,
            status: 'active',
            unit: 'pack',
            tags: JSON.stringify(['sparklers', 'gold', 'premium', 'weddings', 'premium-quality']),
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            slug: 'color-flower-pot',
            name: 'Color Flower Pot',
            description: 'Beautiful flower pot that erupts with colorful flames reaching heights up to 10 feet. Creates a stunning visual display with multiple color variations. Safe for ground display and family enjoyment.',
            categoryId: 3,
            sku: 'FP001',
            stock: 300,
            status: 'active',
            unit: 'piece',
            tags: JSON.stringify(['flower-pots', 'colorful', 'safe', 'family', 'ground-display']),
            createdAt: new Date('2024-01-19').toISOString(),
            updatedAt: new Date('2024-01-19').toISOString(),
        },
        {
            slug: 'big-flower-pot',
            name: 'Big Flower Pot',
            description: 'Big and powerful flower pot with magnificent color explosions reaching up to 20 feet in height. Long-lasting display with sparkling golden effects and colorful flames.',
            categoryId: 3,
            sku: 'FP002',
            stock: 150,
            status: 'active',
            unit: 'piece',
            tags: JSON.stringify(['flower-pots', 'mega-size', 'powerful', 'spectacular', 'premium']),
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },
        {
            slug: 'sky-rocket-small',
            name: 'Sky Rocket Small',
            description: 'Small-sized sky rockets that climb rapidly to create spectacular aerial displays. Burst into colorful stars and patterns in the sky. Perfect first introduction to aerial fireworks.',
            categoryId: 2,
            sku: 'RK001',
            stock: 400,
            status: 'active',
            unit: 'piece',
            tags: JSON.stringify(['rockets', 'aerial', 'sky-display', 'beginner-friendly', 'colorful']),
            createdAt: new Date('2024-01-21').toISOString(),
            updatedAt: new Date('2024-01-21').toISOString(),
        },
        {
            slug: 'sky-rocket-large',
            name: 'Sky Rocket Large',
            description: 'Large sky rockets with powerful propulsion that soar high into the sky creating magnificent aerial bursts and patterns. Multiple color and effects combination for stunning displays.',
            categoryId: 2,
            sku: 'RK002',
            stock: 200,
            status: 'active',
            unit: 'piece',
            tags: JSON.stringify(['rockets', 'large', 'powerful', 'aerial-show', 'premium']),
            createdAt: new Date('2024-01-22').toISOString(),
            updatedAt: new Date('2024-01-22').toISOString(),
        },
        {
            slug: 'diwali-special-gift-box',
            name: 'Diwali Special Gift Box',
            description: 'Carefully curated gift box containing variety of firecrackers including sparklers, chakras, flower pots, and rockets. Perfect gift for friends and family during Diwali celebrations.',
            categoryId: 3,
            sku: 'GB001',
            stock: 100,
            status: 'active',
            unit: 'box',
            tags: JSON.stringify(['gift-box', 'diwali', 'variety-pack', 'family-friendly', 'festive']),
            createdAt: new Date('2024-01-23').toISOString(),
            updatedAt: new Date('2024-01-23').toISOString(),
        },
        {
            slug: 'family-pack-gift-box',
            name: 'Family Pack Gift Box',
            description: 'Family-friendly gift box containing collection of different firecrackers including sparklers, flower pots, and safe crackers. Ideal for celebrating festivals with your loved ones.',
            categoryId: 3,
            sku: 'GB002',
            stock: 80,
            status: 'active',
            unit: 'box',
            tags: JSON.stringify(['gift-box', 'family', 'safe-collection', 'festive', 'loved-ones']),
            createdAt: new Date('2024-01-24').toISOString(),
            updatedAt: new Date('2024-01-24').toISOString(),
        },
        {
            slug: 'wholesale-combo-a',
            name: 'Wholesale Combo A',
            description: 'Wholesale combo pack with 50 assorted firecracker units. Includes rockets, sparklers, flower pots, and various novelty items at discounted wholesale rates. Perfect for bulk purchase.',
            categoryId: 3,
            sku: 'WC001',
            stock: 50,
            status: 'active',
            unit: 'pack',
            tags: JSON.stringify(['wholesale', 'bulk', 'combo-pack', 'discount', 'assorted']),
            createdAt: new Date('2024-01-25').toISOString(),
            updatedAt: new Date('2024-01-25').toISOString(),
        },
        {
            slug: 'wholesale-combo-b',
            name: 'Wholesale Combo B',
            description: 'Premium wholesale assortment containing 75 firecracker units. The perfect collection for large celebrations and resale opportunities. Maximum savings on bulk orders.',
            categoryId: 3,
            sku: 'WC002',
            stock: 30,
            status: 'active',
            unit: 'pack',
            tags: JSON.stringify(['wholesale', 'premium', 'large-collection', 'resale', 'bulk-discount']),
            createdAt: new Date('2024-01-26').toISOString(),
            updatedAt: new Date('2024-01-26').toISOString(),
        },
    ];

    await db.insert(products).values(sampleProducts);
    
    console.log('✅ Products seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});